DROP TABLE ALQUILER;
DROP TABLE VIDEO;


CREATE TABLE RESTAURANTE 
(
  ID NUMBER NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
  REPRESENTANTE VARCHAR2(255 BYTE) NOT NULL,
  TIPO_COMIDA VARCHAR2(255 BYTE) NOT NULL,
  PAGINA_WEB VARCHAR2(255 BYTE),
  CONSTRAINT RESTAURANTE_PK PRIMARY KEY (ID)
);

CREATE TABLE ZONA
(
 
);
CREATE TABLE PRODUCTO
(

);

CREATE TABLE MENU
(
);

CREATE TABLE INGREDIENTE
(
);

CREATE TABLE ADMINISTRADOR
(
);

CREATE TABLE CLIENTE
(
);

CREATE TABLE GERENTE
(
);

CRETE TABLE RESERVA(
);

CREATE TABLE USUARIO 
(
  ID NUMBER NOT NULL,
  VIDEO_ID2 NUMBER,
  USER_NAME VARCHAR2(255 BYTE), 
  CONSTRAINT ALQUILER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_VIDEO2 FOREIGN KEY (VIDEO_ID2) REFERENCES VIDEO(ID)
);

INSERT INTO RESTAURANTE(ID,NAME,DURATION) values (1,'Harry Potter',120);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (2,'Orgullo y Prejuicio',200);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (3,'Furia de Titanes',140);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (4,'Piratas del Caribe',100);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (5,'Avatar',150);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (6,'El Señor de los Anillos',130);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (7,'Sense 8',200);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (8,'Game of Thrones',160);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (9,'Drake and Josh',120);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (10,'The Crown',150);
INSERT INTO RESTAURANTE (ID,NAME,DURATION) VALUES (11,'La Mujer Maravilla',100);


INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (1,1,'Jack');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (2,1,'Juan');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (3,2,'Pedro');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (4,5,'Jack');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (5,10,'Nick');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (6,11,'Jack');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (7,4,'Sara');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (8,7,'Jack');
INSERT INTO USUARIO (ID,VIDEO_ID2,USER_NAME) VALUES (9,7,'Jack');


COMMIT;


